//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace s2.s2Utils.Logic.Tests
{
    using System;
    using System.Collections.Generic;
    using System.CodeDom.Compiler;
    using s2.s2Utils.Logic.Base.Interfaces;
    using PropertyChanged;
    using System.ComponentModel;
    
    [GeneratedCode("Entity Framework", "6.1")]
    [ImplementPropertyChanged]
    public partial class Person : IEntity
    {
    
    	/// <summary>
    	/// Occurs after the value of a property changed.
    	/// </summary>
    	public event PropertyChangedEventHandler PropertyChanged;
    
    	public object Clone()
    	{
    		var copy = (IEntity)MemberwiseClone();
    		copy.Id = 0;
    		return copy;
    	}    
    
            
        public long Id { get; set; }
            
        public string Firstname { get; set; }
            
        public string Lastname { get; set; }
            
        public Nullable<System.DateTime> BirthDate { get; set; }
    
    
    	public override int GetHashCode()
        {
    		return  ((Firstname != null) ? Firstname.GetHashCode() : 0) ^ 
    				((Lastname != null) ? Lastname.GetHashCode() : 0) ^ 
    				((BirthDate != null) ? BirthDate.GetHashCode() : 0);
        }
    }
}
